apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "counterapi.fullname" . }}
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
data:
  REDIS_HOST: "{{ include "counterapi.fullname" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  DB_NAME: "{{ .Values.database.name }}"
  DB_USER: "{{ .Values.database.user }}"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_PASSWORD: "{{ .Values.database.password }}"
  METRICS_BASIC_AUTH: "{{ .Values.metrics.authentication.enabled }}"
  METRICS_BASIC_AUTH_USERNAME: "{{ .Values.metrics.authentication.username }}"
  METRICS_BASIC_AUTH_PASSWORD: "{{ .Values.metrics.authentication.password }}"
