apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "counterapi.fullname" . }}
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
data:
  REDIS_HOST: "{{ include "counterapi.fullname" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  DB_HOST: "{{ .Values.pgbouncer.host }}"
  DB_PORT: "{{ .Values.pgbouncer.port }}"
