{{- if .Values.kargo.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: dev
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
stage: dev
enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: production
  labels:
    {{- include "counterapi.labels" . | nindent 4 }}
stage: production
enableAutoPromotion: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promoters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-promoter
subjects:
  - kind: Group
    name: system:masters
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  subscriptions:
    repos:
      images:
        - repoURL: {{ .Values.image.repository }}
          semverConstraint: ^0.1.0
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: {{ .Values.kargo.argocd.appName }}-dev
        appNamespace: {{ .Values.kargo.argocd.namespace }}
        sourceUpdates:
          - repoURL: {{ .Values.kargo.argocd.repoURL }}
            helm:
              images:
                - image: {{ .Values.image.repository }}
                  key: image.tag
                  value: Tag
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: {{ .Values.kargo.argocd.appName }}-prod
        appNamespace: {{ .Values.kargo.argocd.namespace }}
        sourceUpdates:
          - repoURL: {{ .Values.kargo.argocd.repoURL }}
            helm:
              images:
                - image: {{ .Values.image.repository }}
                  key: image.tag
                  value: Tag
{{- end }}
