apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:counterapi/counterapi.git
    targetRevision: master
    path: kubernetes/application
    directory:
      recurse: true
  destination:
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
