version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/counterapi/api
linters:
  default: standard
  exclusions:
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true
    # Predefined exclusion rules.
    # Default: []
    presets:
      - std-error-handling
      - common-false-positives
    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck


