version: 2
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

settings:
  goimports:
    local-prefixes: github.com/counterapi/api

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - gocyclo
        - errcheck
        - gosec
        - dupl
        - funlen
        - testpackage

linters:
  default: standard
