version: "3.9"
services:
  counterapi_api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    networks:
      - counterapi_api
    depends_on:
      - counterapi_api_database
      - counterapi_api_redis
      - counterapi_prometheus
    environment:
      - DB_HOST=counterapi_api_database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - REDIS_HOST=counterapi_api_redis
      - REDIS_PORT=6379
      - REDIS_DB=14
      - RATE_LIMIT_INTERVAL_SECONDS=60
      - RATE_LIMIT_CAPACITY=10
      - RATE_LIMIT_KEY_PREFIX=counter-api-old-ratelimit

  counterapi_prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - counterapi_api

  counterapi_api_database:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - counterapi_api:/var/lib/postgresql/data
    networks:
      - counterapi_api

  counterapi_api_redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - counterapi_api:/redis/data
    networks:
      - counterapi_api

networks:
  counterapi_api:
    driver: bridge

volumes:
  counterapi_api:
    driver: local