name: Tests

on:
  pull_request:

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: go test
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

  vet:
    name: go vet and lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: go vet
        run: go vet ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1